# Generated by Django 2.1.2 on 2019-06-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0002_auto_20190531_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_pedido',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='detalle_pedido',
            name='id',
        ),
        migrations.RemoveField(
            model_name='detalle_pedido',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='detalle_pedido',
            name='total',
        ),
        migrations.AddField(
            model_name='detalle_pedido',
            name='nombreProducto',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='detalle_pedido',
            name='precioProducto',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='detalle_pedido',
            name='codigoPedido',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
