# Generated by Django 2.1.2 on 2019-05-10 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigoProducto', models.AutoField(primary_key=True, serialize=False)),
                ('fotoProducto', models.ImageField(upload_to='./media/')),
                ('nombreProducto', models.CharField(blank=True, max_length=30)),
                ('precioProducto', models.CharField(blank=True, max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=30)),
                ('stockProducto', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
