# Generated by Django 2.1.2 on 2019-06-04 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(blank=True, max_length=6)),
                ('precio', models.CharField(blank=True, max_length=6)),
                ('total', models.CharField(blank=True, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('codigoPedido', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.CharField(blank=True, max_length=6)),
                ('fecha', models.DateField()),
                ('cliente', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='detalle_pedido',
            name='codigoPedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.Pedido'),
        ),
        migrations.AddField(
            model_name='detalle_pedido',
            name='codigoProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.Producto'),
        ),
    ]
