# Generated by Django 2.1.2 on 2019-06-04 01:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0002_auto_20190603_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
