# Generated by Django 2.1.2 on 2019-06-04 21:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0004_auto_20190604_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('codigoCompra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fecha',
        ),
        migrations.AddField(
            model_name='compra',
            name='codigoPedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.Pedido'),
        ),
    ]
